# name
name: build_countingbook_app

# trigger
on:
- push

# one or more jobs
jobs:
    build_app:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "github ${{ github.ref_name }}"
            - id: s02
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - id: s03
              uses: actions/checkout@v5
            - id: s04
              # install Angular cli & install packages from packages.json
              run: npm i -g @angular/cli && npm ci
            - id: s05
              # build the application
              run: ng build
            - id: s06
              run: ls -l dist/countingbook/browser/
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v3.0
              with:
                publish-dir: 'dist/countingbook/browser'
                production-deploy: true
                production-branch: main
                github-token: ${{ secrets.GITHUB_TOKEN }}
                deploy-message: "Deploy from GitHub Actions"
                enable-pull-request-comment: false
                enable-commit-comment: true
                overwrites-pull-request-comment: true
                env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                timeout-minutes: 1
            