# name
name: build_countingbook_app

# trigger
on:
- push

# one or more jobs
jobs:
    build_app:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "github ${{ github.ref_name }}"