# name
name: build_countingbook_app

# trigger
on:
- push

# one or more jobs
jobs:
    build_app:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "github ${{ github.ref_name }}"
            - id: s02
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - id: s03
              uses: actions/checkout@v5
            - id: s04
              # install Angular cli & install packages from packages.json
              run: npm i -g @angular/cli && npm ci
            - id: s05
              # build the application
              run: ng build
            - id: s06
              run: ls -l dist/countingbook/browser/
            