# name
name: new_tag

# trigger
on:
    push:
        tags:
            - **

# one or more jobs
jobs:
    new_tag:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "There is a new release"