# name
name: new_tag

# trigger
on:
  push:
    tags:
      - v**

jobs:
    new_tag:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "A commit is being tagged"